version: "3.7"

networks:
  budget_tracker:

services:
  core:
    build:
      context: .
      args:
        user: laravel
        uid: 1000
    ports:
      - "9000:9000"
    restart: unless-stopped
    working_dir: /var/www/budget_tracker/src
    volumes:
      - ./src:/var/www/budget_tracker/src
    networks:
      - budget_tracker

  nginx:
    image: nginx:stable-alpine
    container_name: budget_tracker-nginx
    restart: unless-stopped
    ports:
      - "8044:80"
    volumes:
      - ./src:/var/www/budget_tracker/src
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - core
    networks:
      - budget_tracker